### ISSUE TITLE
Design: Enable Kopia file copy

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#1046]
Technical requirements to add kopia as the default file copy option.
 
- Upstream Design: https://github.com/vmware-tanzu/velero/blob/v1.10.0/design/unified-repo-and-kopia-integration/unified-repo-and-kopia-integration.md

 ## To-do

- [x ] ResticRepository CR is renamed as BackupRepository CR ( as velero 1.10 )
- [ ] There is a new installation flag --pod-volume-backup-uploader, we need to add support for this via DPA
- [ x ] Restic daemonset is renamed as node-agent, we might have already tackled this as part of our routine rebase
- [ ] Documentation: There is a Velero CLI change, Velero restic repo get is not Velero repo get
- [ ] Documentation: Restic name presense is removed from APIs as well like defaultVolumesToRestic is now defaultVolumesToFSBackup
   - [ ] Eng:  if defaultVolumesToFSBackup is a server param this needs investigation
- [ ] Make Kopia the default
- [ ] Document user requirements
  - [ ] need to rebackup after installing 1.3.0 or flip option to use use restic.

Decent issue for newer folks

**Comment by weshayutin** [comment]
related to #1057

**Comment by shubham-pampattiwar** [comment]
Changes that we need to be aware and support via OADP involve the following (but not limited to):
- `ResticRepository` CR is renamed as `BackupRepository` CR
- There is a new installation flag `--pod-volume-backup-uploader`, we need to add support for this via DPA
- Restic daemonset is renamed as `node-agent`, we might have already tackled this as part of our routine rebase 
- There is a Velero CLI change, `Velero restic repo get` is not `Velero repo get` 
- Restic name presense is removed from APIs as well like `defaultVolumesToRestic` is now `defaultVolumesToFSBackup`

**Comment by sseago** [comment]
Investigation required for proper documentation. Main concern is what happens when you need to a restore a backup with a different uploader than the currently configured one. For example, you configure the new OADP 1.3 install to use kopia. What happens when you attempt to restore a restic backup (from 1.2 or 1.3). Will it succeed? Will it fail with a sane error message (i.e. "restic uploader is not configured...")? What is the proper procedure for restoring from restic when kopia is enabled (or vice versa)? "pause schedules; set DPA to use restic uploader; (don't run any backups); restore; upon restore completion, set DPA to use kopia uploader; unpause schedules", etc.

**Comment by tsanders-rh** [comment]
Is the plan here to support both kopia and restic as configurable options by the end-user through their DPA? or on a per backup/restore CR?  Is it possible for us to detect or introspect the s3 data to determine if the backup is kopia or restic based?

**Comment by weshayutin** [comment]
@tsanders-rh 
The discussion we've had thus far in design meetings has to been enable either kopia or restic in the dpa only.   Both restic and kopia would be fully supported in 1.3.0 but would be a choice made in the DPA.   

We raised this issue yesterday again.  I challenged that notion based on what I read in the design but I didn't have the details handy.   The question I am raising is can [restic, kopia] be a choice in Backup CR.

@sseago here is what I found in the design..  
https://github.com/vmware-tanzu/velero/blob/v1.10.0/design/unified-repo-and-kopia-integration/unified-repo-and-kopia-integration.md#path-switch--coexist

* Add the “uploader-type” option as a parameter of the Velero server. The parameters will be set by the installation. Currently the option has two values, either "restic" or "kopia" (in future, we may add other file system uploaders, then we will have more values).

* Add a "uploaderType" value in the PodVolume Backup/Restore CR and a "repositoryType" value in the BackupRepository CR. "uploaderType" currently has two values , either "restic" or "kopia"; "repositoryType" currently has two values, either "restic" or "kopia" (in future, the Unified Repository could opt among multiple backup repository/backup storage, so there may be more values. This is a good reason that repositoryType is a multivariate flag, however, in which way to opt among the backup repository/backup storage is not covered in this PR). If the values are missing in the CRs, it by default means "uploaderType=restic" and "repositoryType=restic", so the legacy CRs are handled correctly by Restic.

@sseago @shubham-pampattiwar please poke around the code for and let's double check if restic, kopia is a binary choice only at install time.

Thanks

**Comment by weshayutin** [comment]
@shawn-hurley both restic and kiopia will be supported, what we are saying for 1.3.0 is that kopia will be the default.

**Comment by shawn-hurley** [comment]
I am saying that they have to work for restore simultaneously, not that you have to select the right one based on your backups.

**Comment by sseago** [comment]
@shawn-hurley "SHOULD support both being restored regardless of the binary choice for some time." -- first question is not what SHOULD work but what DOES work (in Velero 1.11/1.12). I may be wrong -- my initial impression was only one was active at a time. And you're right -- that's an awful user experience. But we need to actually read the code (or try it out) and see whether this is actually true.

**Comment by sseago** [comment]
Also, just to make it clear, *this* task is to bring support into OADP for Kopia backup/restore *as it is currently supported upstream*. If it turns out that simultaneous support for kopia and restic restores is not supported in the current (1.11) upstream Velero codebase, any changes to this would be a separate github issue for (upstream-first) development of this feature.

**Comment by tsanders-rh** [comment]
@sseago So you have confirmed that in Velero upstream (1.11) data transfer (kopia or restic) is a choice made during install?

**Comment by weshayutin** [comment]
@sseago Agreed we are only supporting the upstream functionality in 1.3.0. 100%
However, according to the design, and after poking around the code it does appear both restic and kopia backup and restore is supported w/o changing server args.  Please read through the design and poke around the code to confirm.

**Comment by sseago** [comment]
@tsanders-rh it is a choice made during install. Here's the documentation for the flag passed to `velero server` (in the deployment cmd args):
```
      --uploader-type string                                Type of uploader to handle the transfer of data of pod volumes (default "restic")
```
For backups, I'm pretty sure that only the selected method will ever be used (i.e. you can't configure kopia and run a restic backup), since there is no equivalent uploader-type field in the backup spec.

The open question is for restores. I need to dig into the code and determine whether a restic restore will work with a kopia-configured Velero.

**Comment by sseago** [comment]
@tsanders-rh OK, I just spent some more time digging into the restic and kopia codebase, and it looks like my earlier concern was unwarranted. The code is pretty clear that for *backups*, the uploader type (i.e. kopia vs. restic) is taken from the server settings (i.e. DPA config), but for *restores*, we grab uploader type from the backup (specifically, the PodVolumeBackup CR). 
In other words, what @shawn-hurley said "SHOULD" be done is exactly what the code is doing.

Note that I haven't actually tested this with real restic backups, restoring to a kopia-configured Velero -- but, I think at this point I'm satisfied that any failures there represent bugs we can fix rather than UX and/or design flaws.

**Comment by sseago** [comment]
So ignore anything I said above about needing to restart velero to restore, etc.

**Comment by weshayutin** [comment]
@mpryc read through https://redhat-internal.slack.com/archives/C0144ECKUJ0/p1688737460687369
Let's follow up in scrum.

1.  Enabling the option for either restic or kopia is 100% for sure
2.  Goal is make kopia the default 
  1.  doc and messaging is required 
  2.  consider ensuring the operator does NOT automatically upgrade from 1.2.x -> 1.3.x
  3.   Ensure the operator install page highlights the change from restic to kopia and points to doc

@shawn-hurley @sseago does this summarize our understanding decently?

**Comment by shawn-hurley** [comment]
Yeah that does seem like a good digest of the flow of the convo

**Comment by tsanders-rh** [comment]
Makes good sense.  I am assuming if kopia will be default in 1.3, that it will be fully supported and NOT tech-preview?

**Comment by sseago** [comment]
To avoid changing customer settings silently behind their backs, I'd suggest leaving Restic as the default for 1.3 but making kopia fully-supported. The reason is that we don't want to have upgrading customers suddenly using kopia instead of restic with no notice. My suggestion:
1) for 1.3, add UploaderType support to the DPA for velero install. If DPA spec does not supply this field, then the controller updates spec to explicitly set it to "restic", and velero deployment is created with restic UploaderType
2) This means anyone upgrading from 1.2 will get their existing DPAs updated with explicit Restic choice. Any new DPAs created post-1.3 install without the setting will get "restic", but they'll get "kopia" with an explicit choice
3) For 1.4, flip the default to "kopia" -- upgrading users with existing 1.3 DPAs will already have an explicit choice, so it won't be changed on them without warning. New DPAs created post-1.4-install without a choice will get "kopia" -- if they choose "restic" that's what they'll get.

I think that this is the only way to move to fully-supported kopia without changing uploader type on users without warning.

**Comment by sseago** [comment]
@tsanders-rh My opinion is that we should fully support kopia in 1.3 regardless of our decision on default choice. This will better prepare us for future deprecation and removal of restic.

**Comment by weshayutin** [comment]
@sseago Please re-read my comment.  We can change the operator to NOT automatically upgrade customers from 1.2 -> 1.3 AFAICK.  I want to confirm with some folks first but it seems reasonable to change the operator upgrade path and highlight the change during the install.

**Comment by sseago** [comment]
@weshayutin I got that. But I'm still thinking  that if we follow my suggestion, it may be a clearer path. It allows upgrades to *not* change uploader type existing installs (regardless of whether they're automatic), allowing users to make their own choice of when to move to restic, post-upgrade. It allows for a transition from 1.2->1.3 where we enable kopia without changing the default (and all existing DPAs get restic as uploader type explicitly listed, vs. nothing being listed there), and then a transition from 1.3->1.4 where we change the default value, but since all 1.3 installs already have "restic" explicitly in the DPA (unless they changed to kopia), the default switch won't take anyone by surprise, since it won't affect existing DPAs, it will only be used for new DPAs which don't specify an uploader type.

**Comment by mpryc** [comment]
Design PR: #1101
