### ISSUE TITLE
CVEs

### ISSUE THREAD

**Issue by davidkarlsen** [openshift/oadp-operator#196]
There are a lot of vulnerabilities in the image: https://quay.io/repository/konveyor/oadp-operator/manifest/sha256:3e6d24020434f923a8ec0de43e778a1c0c23db5ac99b8d9ab6fd8acec13e54d9?tab=vulnerabilities - can you update the packages?

**Comment by dymurray** [comment]
@davidkarlsen Thank you for the heads up. Our previous releases were using a version of ansible operator with some CVEs and we have since updated our images for our work to move to a golang-based release. Our latest images are passing security scans without issues. We have no intention of updating the 0.2.x release to fix these vulnerabilities but will ensure 0.3.x does not have any CVEs.

**Comment by dymurray** [comment]
@davidkarlsen Currently targeting 9/29. Will be version 0.3.0.

**Comment by davidkarlsen** [comment]
@dymurray Maybe the readme should be updated with upgrade nodes and what velero version it is?
