### ISSUE TITLE
Bug: parks-app crashes after being restored when hitting the api

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#646]
### Contact Details

whayutin@redhat.com

### Describe bug

parks-app is OLD... afaict it's only value is mongodb.
https://github.com/openshift/oadp-operator/tree/master/tests/e2e/sample-applications/parks-app

Let's replace parks app w/ the same app we use for mariadb (todolist).
This will allow for[ data validation across db backends ](https://github.com/openshift/oadp-operator/pull/624)

We have the todolist app working with MongoDB.
https://github.com/weshayutin/todolist-mongo-go

### What happened?

A bug happened!

### OADP Version

1.0.1 (Stable)

### OpenShift Version

4.10

### New issue

- [X] This issue is new

**Comment by weshayutin** [comment]
@deepakraj1997 @hhpatel14  FYI

**Comment by deepakraj1997** [comment]
Further debug of this issue:

after i did a backup and restore, we have the same pods running initially but after i hit the parks REST API, it doesnt work, however, another deployment get triggered due to a change in build config: https://github.com/openshift/oadp-operator/blob/master/tests/e2e/sample-applications/parks-app/manifest4.8.yaml#L69-L77

After restore
![image](https://user-images.githubusercontent.com/36184070/164760384-1ce9ccf8-9d94-4633-8b00-cdb5b7634e4e.png)

Hitting the API
![image](https://user-images.githubusercontent.com/36184070/164760404-747015fb-f421-4b7f-8b0f-c6f9a76e09c7.png)

New Deployment trigger
![image](https://user-images.githubusercontent.com/36184070/164760418-0bcf9161-9fdf-47d5-8163-9fd028845c7e.png)

After this it works,

**Comment by kaovilai** [comment]
I think the verification function should wait a few seconds and only check the last deployment (restify-2).

**Comment by kaovilai** [comment]
Whatever replacement is should remains a deploymentconfig with buildconfig which is a usecase that OADP currently [requires a workaround](https://github.com/openshift/oadp-operator/blob/master/docs/TROUBLESHOOTING.md#issue-with-backuprestore-of-deploymentconfig-using-restic) on to restore successfully.

**Comment by weshayutin** [comment]
oh @kaovilai so just to make sure I 100% understand what you are say.
Replace the container definition in the manifest and have the app built via an openshift build-config.
Is that correct?  Happy to do it if so.

**Comment by kaovilai** [comment]
Yes. That would be great!
