### ISSUE TITLE
Remove PV and PVC nodeAffinity

### ISSUE THREAD

**Issue by deanpeterson** [openshift/oadp-operator#894]
I made an oadp backup on a full cluster and am trying to restore on Single Node Openshift in aws. Everything was great until I ran into the PVs nodeaffinity settings of a specific availability zone. Since my Single Node Openshift is not in the original availability zone it's giving me an error. Is there a way to eliminate the nodeaffinity on the pv either in the backup or restore using the oadp operator?

The solution recommended here unfortunately doesn't work because any changes to the gp2-csi storage class just get overwritten and restored to the original values: https://access.redhat.com/solutions/4241261

**Comment by deanpeterson** [comment]
I've tried a number of things with limited success. I did add another storageclass simply named gp2 that let's me put in the allowedTopoligies section but that doesn't matter when OADP is auto creating the PV with nodeAffinity in it. I also tried pre-creating the PV. That did allow the oadp operator to skip pv creation on one app but I'm having a hard time getting that strategy to work with an instance of keycloak and its postgresql database. Even though I can probably get the approach of pre-creating the pv or pvc, that does not scale, it's hacky and super painful. There really is no way to tell OADP, "hey, when you're copying PVs between clusters, DO NOT apply nodeAffinity from the previous cluster?

**Comment by kaovilai** [comment]
If node affinity doesn't apply at restore. It also means it is not required to work.. therefore it would be best that node affinity is removed from the backup cluster.

Node affinity removal cannot be done automatically for everyone, because some workload requires it when restoring to the same cluster.

There is currently to flag I am aware of to remove node affinity.

You could wait for a feature to be built into velero and then wait for it to arrive to oadp. Alternatively, you could author a velero plugin that does this for you.

**Comment by deanpeterson** [comment]
I don't really want to remove it but it needs to be changed to the new availability zones in the new cluster. There is no way to at least change the nodeAffinity?

**Comment by kaovilai** [comment]
Nothing implemented right now. There are proposals to substitute fields on
restore but as I understand it it's not yet merged.


/remove-lifecycle stale

**Comment by kaovilai** [comment]
@deanpeterson good news, this was addressed in https://github.com/vmware-tanzu/velero/pull/6452

**Comment by kaovilai** [comment]
closed by https://github.com/vmware-tanzu/velero/pull/6452
