### ISSUE TITLE
OADP does not support Third-Party BackupStorageLocation providers

### ISSUE THREAD

**Issue by phuongatemc** [openshift/oadp-operator#91]
The creation of oadp-registry is supported only for aws as a provider for BSL.  When configuration for DataDomain BSL is included in the Velero yaml (see https://justpaste.it/2iaqe), neither BSL nor oadp-registry is created.

See related issue [https://github.com/konveyor/oadp-operator/issues/66](url)

**Comment by dymurray** [comment]
The issue here is that OADP forces you to use a plugin for BSLs that we support (AWS, Azure, GCP). The problem is that this doesn't allow a user to use custom plugins for their own BSLs. Datadomain has their own BSL plugin and we need to be able to support the user's configuration of third party plugins.

**Comment by dymurray** [comment]
In the move to a golang operator, this shouldn't be an issue since we are doing a pure passthrough of BSL creation in our spec.

We will want to ensure we don't do any extra validation to prevent this use case. We will also need to likely disable the registry for use cases like this.
